import { AlertTriangle, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AdminShell } from "@/layouts/AdminShell";
import { listAdmsDevices, listAdmsGlobalTransactions, type AdmsDevice, type AdmsGlobalTransaction } from "@/lib/attendance";

function fmt(value:string){return new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(new Date(value));}

export function AdminAdmsGlobalTransactionsPage(){
 const [items,setItems]=useState<AdmsGlobalTransaction[]>([]); const [devices,setDevices]=useState<AdmsDevice[]>([]);
 const [deviceId,setDeviceId]=useState(""); const [mapping,setMapping]=useState<"all"|"mapped"|"unmapped">("all"); const [q,setQ]=useState(""); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{void Promise.all([listAdmsGlobalTransactions({deviceId:deviceId||undefined,mapping}),listAdmsDevices()]).then(([tx,dev])=>{setItems(tx.items);setDevices(dev.items);setError(null);}).catch(c=>setError(c instanceof Error?c.message:"Transaksi tidak dapat dimuat."));},[deviceId,mapping]);
 const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return n?items.filter(i=>[i.pin,i.employeeName??"",i.employeeNumber??"",i.deviceName??"",i.serialNumber].join(" ").toLowerCase().includes(n)):items;},[items,q]);
 return <AdminShell active="attendance-adms" title="Transaksi ADMS Global" description="Cari scan fingerprint lintas seluruh mesin tanpa membuka perangkat satu per satu.">
  <div className="mb-4 flex flex-wrap gap-2"><a className="h-10 rounded-xl border px-3 py-2 text-xs font-bold" href="/admin/attendance/adms">← Back Office ADMS</a><select className="h-10 rounded-xl border px-3 text-sm" value={deviceId} onChange={e=>setDeviceId(e.target.value)}><option value="">Semua mesin</option>{devices.map(d=><option key={d.id} value={d.id}>{d.displayName||d.serialNumber}</option>)}</select><select className="h-10 rounded-xl border px-3 text-sm" value={mapping} onChange={e=>setMapping(e.target.value as typeof mapping)}><option value="all">Semua mapping</option><option value="mapped">Sudah mapping</option><option value="unmapped">Belum mapping</option></select><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className="h-10 rounded-xl border pl-9 pr-3 text-sm" placeholder="Cari PIN/pegawai/mesin…" value={q} onChange={e=>setQ(e.target.value)}/></label></div>
  {error?<div className="mb-4 flex gap-2 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle className="h-4 w-4"/>{error}</div>:null}
  <section className="overflow-hidden rounded-2xl border border-border/70 bg-white shadow-[var(--shadow-soft)]"><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-surface text-xs text-muted-foreground"><tr><th className="p-3">Waktu mesin</th><th className="p-3">Diterima</th><th className="p-3">Mesin</th><th className="p-3">PIN</th><th className="p-3">Pegawai</th><th className="p-3">Unit</th><th className="p-3">Mapping</th></tr></thead><tbody className="divide-y">{filtered.map(i=><tr key={i.id}><td className="p-3">{fmt(i.occurredAt)}</td><td className="p-3">{fmt(i.receivedAt)}</td><td className="p-3"><p className="font-semibold">{i.deviceName||i.serialNumber}</p><p className="font-mono text-xs text-muted-foreground">{i.serialNumber}</p></td><td className="p-3 font-mono">{i.pin}</td><td className="p-3">{i.employeeName??"—"}<p className="text-xs text-muted-foreground">{i.employeeNumber??""}</p></td><td className="p-3">{i.unitName??"—"}</td><td className="p-3">{i.mappingState==="mapped"?"Terhubung":"Belum mapping"}</td></tr>)}{filtered.length===0?<tr><td colSpan={7} className="p-8 text-center text-muted-foreground">Tidak ada transaksi pada filter ini.</td></tr>:null}</tbody></table></div></section>
 </AdminShell>;
}
